---
title: "Wildlife Ilha do Meio and Rata"
author: "Tati Micheletti"
date: "10/19/2023"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries

```{r libs}
if(!require("Require")){
    install.packages("Require")
}
library("Require")
Require("googledrive")
Require("reproducible")
Require("data.table")
Require("unmarked")
devtools::install_github("mikemeredith/AHMbook")
# Require("MASS")
# Require("lattice")
# Require("glmmTMB")
# Require("performance")
# source("test_ZI.R")
# If any packages were installed here, restart your session and re-run the code!
```

Negative Binomial Models are appropriate for counts, especially if there is variability in the underlying rate of events.

```{r loadAndCheckData}
# https://groups.google.com/g/unmarked/c/vfOwosiCL0s
# https://groups.google.com/g/unmarked/c/crdKGryFsMg?pli=1
 
DT <- fread("data/IPA.csv")
DT[, "Date" :=  as.Date(with(DT,paste(Year,Month,Day,sep="-")),"%Y-%m-%d")]
DT[, "originDate" :=  as.Date(paste(Year,1,1,sep="-"),"%Y-%m-%d")]
julDate <- rbindlist(lapply(X = 1:NROW(DT), function(rid){
  currRow <- DT[rid,]
  dt <- currRow[["Date"]]
  orig <- currRow[["originDate"]]
  jd <- data.table(JulianDate = julian.Date(x = dt, 
                                             origin = orig))
  return(jd)
}))
DT[, "JulianDate" :=  julDate]
DT[, "timeSinceStartEradication" :=  julian.Date(x = Date, origin = as.Date(min(unique(DT$Date))))]
DT[, pointID := 1:.N, by = c("Original_Landscape", "Date", "Island", "Species")]
DT[, transectID := LETTERS[as.numeric(as.factor(Original_Landscape))]]
DT[, site := paste0(transectID, pointID)]
mabuiaRata <- DT[Island == "Ilha Rata" & Species == "Trachylepis atlantica",]

################################# ILHA DO MEIO #################################
# First we subset the data to the interested place and the species
mabuiaMeio <- DT[Island == "Ilha do Meio" & Species == "Trachylepis atlantica",]

# Drop what we don't need, or don't want: 
# Island, Year, Month, Day, Species, Radius, Original_Landscape, originDate
toRemove <- c("Island", "Year", "Month", "Day", "Species", 
              "Radius", "Original_Landscape", "originDate",
              "pointID", "transectID")
mabuiaMeio <- mabuiaMeio[, (toRemove) := NULL]

# Now we make the needed objects:

# y --> Matrix with observations where rows represent each site (unmarked calls this 'M'), and columns the 
# (increasing) sampling occasion (i.e., the time series of counts, representing 
# each visit), which unmarked calls 'T'. The value is the Counts.
finalCounts <- dcast(mabuiaMeio, site ~ Date, value.var = "Counts")
y <- as.matrix(finalCounts[,-1]) # Convert to matrix

# obsCov --> Observation covariates are the ones that vary per sampling occasion.
# This object is a named list of each covariate, which are data frames of rows 
# representing each site and the columns each sampling occasion. 
# Examples are: observerID, JulianDate, timeSinceStartEradication
# observerID <- matrix(as.numeric(as.factor(as.matrix(dcast(mabuiaMeio, site ~ Date, value.var = "Observer")[,-1]))),
#                         nrow = NROW(y), ncol = NCOL(y), byrow = FALSE)
# JulianDate <- matrix(as.numeric(as.matrix(dcast(mabuiaMeio, site ~ Date, value.var = "JulianDate")[,-1])),
#                         nrow = NROW(y), ncol = NCOL(y), byrow = FALSE)
# timeSinceStartEradication <- matrix(as.numeric(as.matrix(dcast(mabuiaMeio, site ~ Date, 
#                                                value.var = "timeSinceStartEradication")[,-1])),
#                                     nrow = NROW(y), ncol = NCOL(y), byrow = FALSE)
observerID <- as.matrix(dcast(mabuiaMeio, site ~ Date, value.var = "Observer")[,-1])
JulianDate <- as.matrix(dcast(mabuiaMeio, site ~ Date, value.var = "JulianDate")[,-1])
timeSinceStartEradication <- as.matrix(dcast(mabuiaMeio, site ~ Date, value.var = "timeSinceStartEradication")[,-1])
obsCovs <- list(observerID = observerID,
               JulianDate = JulianDate,
               timeSinceStartEradication = timeSinceStartEradication)

# siteCovs --> Site covariates are fixed through time, varying only among each 
# other. This object is matrix where rows representing each site and the columns 
# each covariate. 
# Examples are: Cover (landscape type)
cover <- data.frame(dcast(mabuiaMeio, site ~ Date, value.var = "Landscape")[,"2018-04-12"])
names(cover) <- "cover"

# numPrimary --> Maximum number of observed primary periods all sites
numPrimary <- 5
# primaryPeriod --> In which primary period each observation happened?
primaryPeriod <- matrix(as.integer(c(
    rep(1, times = NROW(y)),
    rep(2, times = NROW(y)),
        rep(2, times = NROW(y)),
    rep(3, times = NROW(y)),
    rep(4, times = NROW(y))
)), nrow = NROW(y), ncol = NCOL(y), byrow = FALSE)

# But what if I use the time since eradication here instead of as a covariate?! 
# primaryPeriod <- matrix(as.integer(
#   sort(unique(mabuiaMeio$timeSinceStartEradication))), 
#   nrow = NROW(y), ncol = NCOL(y), byrow = TRUE)
# This took a long time... I broke the calculations because I think that what is 
# important is the time between the primary periods, which can be derived from the 
# time since start eradication.
# 
# tmDiff <- unique(mabuiaMeio$timeSinceStartEradication)
# primaryPeriod <- matrix(as.integer(
#   c(0, dist(tmDiff)[1:4])), 
#   nrow = NROW(y), ncol = NCOL(y), byrow = TRUE)

yearlySiteCovs <- list(timeSinceStartEradication = timeSinceStartEradication) 
# If I don't pass this as yearlySiteCov, the model doesn't work...

# Create the unmarkedFrame
mabuiaDF <- unmarkedFramePCO(y = y,
                             siteCovs = cover,
                             obsCovs = obsCovs,
                             numPrimary = numPrimary,
                             primaryPeriod = primaryPeriod, 
                             yearlySiteCovs = yearlySiteCovs
                             )
# Take a look
mabuiaDF
summary(mabuiaDF)

mod <- pcountOpen(lambdaformula = ~1,  # Initial abundance
                  gammaformula = ~1,  # Formula for population growth rate
                  omegaformula = ~1 + timeSinceStartEradication, # Formula for apparent survival probability: I wanted 
                                     # timeSinceStartEradication as cv. 
                                     # However, when "trend", no covariates are 
                                     # allowed here!
                  pformula = ~1 + timeSinceStartEradication, # Formula for detection probability.
                  data = mabuiaDF, 
                  mixture = "NB", # Negative binomial
                  dynamics = "autoreg", # We want the population trend through time
                  immigration = FALSE,
                  K = 150)
mod

(exp(0.000364))





# lambdaformula = ~ 1,  # Initial abundance
# gammaformula = ~ 1,  # Formula for population growth rate
# omegaformula = ~ 1, # Formula for apparent survival probability
# pformula = ~ 1, # Formula for detection probability
# data = umf2,
# mixture = "NB", # Negative binomial
# dynamics = "trend", # We want the population trend through time
# immigration = FALSE,
# K = 50

######### EXAMPLES ########
# Repeated count data with 4 primary periods and
# 2 secondary sampling periods (ie J=2)
y2 <- matrix(c(
    3,4,  2,2,  2,1,  0,1,
    2,3,  4,NA,  2,2,  0,1,
    1,3,  1,1,  0,NA,  0,1,
    4,0,  0,1,  NA,1,  NA,2), nrow=4, ncol=8, byrow=TRUE)

# Site-specific covariates
# If a site-specific covariate is missing, all of the data for that site will
# be discarded (when the covariate is included in the model).
sc2 <- data.frame(cover = c("forested", "forested", "open", "open"))

# Observation-specific covariates
observerID <- matrix(1:2, nrow=4, ncol=8, byrow=FALSE)
daysSinceStartEradication <- matrix(rep(c(0, 1, 30, 31, 60, 61, 80, 82)), nrow=4, ncol=8, byrow=TRUE)
oc2 <- list(
    observerID = observerID,
    # julianDate = matrix(, nrow=4, ncol=8, byrow=TRUE),
    daysSinceStartEradication = daysSinceStartEradication)

# Primary periods of surveys
primaryPeriod2 <- matrix(as.integer(c(
    1,2,2,3,
    1,2,2,3,
    1,2,2,3,
    1,2,2,3)), nrow=4, ncol=4, byrow=TRUE)

# Create the unmarkedFrame
umf2 <- unmarkedFramePCO(y=y2,
                         siteCovs=sc2,
                         obsCovs=oc2,
                         numPrimary=4,
                         primaryPeriod=primaryPeriod2)
# Take a look
umf2
summary(umf2)

mod <- pcountOpen(lambdaformula = ~ cover,  # Initial abundance
                  gammaformula = ~ 1,  # Formula for population growth rate
                  omegaformula = ~1, # Formula for apparent survival probability
                  pformula = ~ observerID, # Formula for detection probability
                  data = umf2,
                  mixture = "NB", # Negative binomial
                  dynamics = "trend", # We want the population trend through time
                  immigration = FALSE,
                  K = 50)
mod

# Parameters spitted out:
# Abundance
# Growth Rate (the finite rate of increase)
# Detection
# Dispersion (α, describes data dispersion -- lower α implies higher variance)

# BUT NOW I NEED TO GET THE PARAMETERS BACK IN THEIR ORIGINAL FORMAT!


```
